pipeline {
    agent any

    environment {
        DOCKER_NETWORK = 'networksecurepulse'
        MYSQL_HOST = 'mysqlcontainer'
        MYSQL_PORT = '3306'
        MYSQL_DB_NAME = 'securepulse'
        MYSQL_USER = 'root'
        MYSQL_PASSWORD = 'root1'
        APP_IMAGE = 'securepulseimage'
        CONTAINER_NAME = 'securepulsecontainer'
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/ayusharora176/FraudDetection.git'
            }
        }

        stage('Build Java Project') {
            steps {
                dir('SecurePulse') {
                    // Remove target folder manually and rebuild the project
                    bat """
                    rmdir /s /q target
                    mvn package -DskipTests
                    """
                }
            }
        }

        stage('Remove Old Container and Image') {
            steps {
                bat """
                docker rm -f %CONTAINER_NAME% || exit 0
                docker rmi -f %APP_IMAGE% || exit 0
                """
            }
        }

        stage('Build Docker Image') {
            steps {
                bat "docker build -t %APP_IMAGE% ./SecurePulse"
            }
        }

        stage('Run New Container') {
            steps {
                bat """
                docker run -d ^
                    --name %CONTAINER_NAME% ^
                    --network %DOCKER_NETWORK% ^
                    -e MYSQL_HOST=%MYSQL_HOST% ^
                    -e MYSQL_PORT=%MYSQL_PORT% ^
                    -e MYSQL_DB_NAME=%MYSQL_DB_NAME% ^
                    -e MYSQL_USER=%MYSQL_USER% ^
                    -e MYSQL_PASSWORD=%MYSQL_PASSWORD% ^
                    -p 8090:8080 ^
                    %APP_IMAGE%
                """
            }
        }
    }

    post {
        success {
            echo '✅ SecurePulse backend deployed successfully on port 8090!'
        }
        failure {
            echo '❌ Deployment failed.'
        }
    }
}
